---
- name: Deploy HTTPS websites
  hosts: all
  become: true
  gather_facts: yes
  tasks:
  - name: Install software
    ansible.builtin.dnf: 
      name:
        - httpd
        - mod_ssl
        - firewalld
      state: latest
  - name: Configure Apache for HTTPS
    template:
      src: templates/ssl.conf.j2
      dest: /etc/httpd/conf.d/ssl.conf
    notify: restart_apache
  - name: Start and enable services
    service:
      name: "{{ item }}"
      state: started
      enabled: true
    loop:
      - httpd
      - firewalld
