---
- name: Deploy HTTPS websites
  hosts: all
  become: true
  gather_facts: yes
  tasks:
  - name: Install software
    ansible.builtin.dnf: 
      name:
        - httpd
        - mod_ssl
        - firewalld
      state: latest
