---
- name: Deploy HTTPS websites
  hosts: all
  become: true
  gather_facts: true
  tasks:
  - name: Install software
      ansible.builtin.dnf: 
        name:
          - httpd
          - mod_ssl
          - firewalld
        state: latest
